language: node_js
node_js: stable
sudo: false

install:
- npm install;

before_script:
- npm run-script clean;

script:
- npm run-script build;

deploy:
  provider: npm
  email: eric@hkasianark.com
  skip_cleanup: true
  api_key:
    secure: 0WpVNOPYqdvzZ6rVBwnJ/9JkN2fYPodAx29lD/BRkgGj1hh4whJOdW34zQmj7+a6948m+OqIpq7DY/ue5yCYqH2L5OCxeLAd4DABZgLYSXlEZ8Ld1GL2CEsT1sWpr1ppxHRKlBJGYoD/ApxErDgdKV5VRxATfzg02SJqrRD+guqSZzVWCyfREVF0T8R6Qosw0hyP2XhgczUEyWcPdLcTS+tRAeKOGkpYqNWPZOnHrrSyJVr++rtgg9mTG0yv1JqqE0bllBrkcQjftiSXb6q/T7/OY+hhQwiVj5mzjRUigfRUHRB9EWQz6bWl4UefdVIq67V3FsmTU3BoTSyYRsvoLK6x1UFEK55O6sKiCvCc41eR50ZUM/1u/vjITOSchrI++L+aC/8/FPFJLL5tiN/YSgqzPpjZG+Q6FHPQNjiE3QS7AQNqNbm9yE61BVVcgJFLG5BFKlIPS0GLsYSVFiUFgq2Cr46F4RaFlc92g8a8t88CsuQF+71TKhO5g1lgyQwIPpD74mRlDfxRNCpJwSkaDeGMwAPjIVGHLckWtfyPzq0aBCwZUUuHkY3WonefKXIIp+eph5p//ANjL500Bi3Ejq/CHkv5/2BXsYGTZDRimOCr7u6m6Q8LAYW6rNVzLgAYaT1+rp00ZYcIVoBuXgJL4VwQWfG2Hz7Vp332gw3gOtQ=
  on:
    tags: true
    branch: master
