language: node_js
node_js: stable
sudo: false

install:
- npm install;

before_script:
- npm run-script clean;

script:
- npm run-script build;

deploy:
  provider: npm
  email: eric@hkasianark.com
  skip_cleanup: true
  api_key:
    secure: zdSS0mH1Au+eu/IjqxJfEx4/fp/3LIi4AhFeNEUqVF/UrVzlozRs97Y7aZKNBaYiTFZXSRYr0eJrMuGgdgM38S6YTr/Vrf+Dx3Kia4Hv8s2wIFq6OToPubieE7oEPp5etNzibT8SdbLNuoe4dXkv8q+s+G91Y95xLbrPubMKPC7ea+uxcj4jEovVGgvtOoW/1k7Y2Ll995j2Y+wFxR58+ZXTbpGPj1YIoc1+I0j7I5/QiKYs9TlnYtEHaXy1M8g2WYLrngqvEYaKZmbcVhPJC9e5+3DEKPhuBi2F2H2yHynDwvOORpfND2EvUjUgMTHjSWjMIK8GxG3GmqOdBnV9/TmeFpZYrbJIq94ys5wMqCDHWoDad6TfBA+8qJzWPFazNuLS9FJaNC7y54f7/JOT0veTTTDH+SQWCT7r7Fuw7JMxLRJpTRzpSgbCL/iXihSO0WqH36XS2r6jGZXYHl8C3JxfeI55OfeKM5sGlkI40lKWtobOKfuOmOLuSmkssNsCSlDuoUtTfHdROsCcDBiyuWwTQItESQtHWv4LUwelDC4tEgpWtjgcYBtM2p6pNm5fJl3Rssr6rtCq8xiV4BOuyUr8+a59IaxQs+0MquxYGNGwA2aI1lKbWyQOv9icftqrRAs+d2QE+rgTTEeNXiWOjQ83IaptTyJp+iajHZjsLEA=
  on:
    tags: true
    branch: master
